export const GET_ARRIVALS = 'GET_ARRIVALS';
export const GET_ARRIVALS_ERROR = 'GET_ARRIVALS_ERROR';
export const GET_ARRIVALS_SUCCESS = 'GET_ARRIVALS_SUCCESS';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';